[tool.bumpversion]
current_version = "1.2.1"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"

[[tool.bumpversion.files]]
filename = "src/oedisi/__init__.py"

[[tool.bumpversion.files]]
filename = "src/oedisi/tools/__init__.py"

[[tool.bumpversion.files]]
filename = "src/oedisi/types/__init__.py"

[[tool.bumpversion.files]]
filename = "src/oedisi/componentframework/__init__.py"

[[tool.bumpversion.files]]
filename = "CITATION.cff"
